"use client"
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "@/styles/globals.css";
import "@/styles/globals.scss";
import React from "react";
import ContextProvider from "@/components/Context";
import { Wagmi } from "./wagmi";
import { Layout } from "antd";
import Header from "@/components/Header";
import Footer from "@/components/Footer";
import StyledComponentsRegistry from "@/lib/AntdRegistry";
const { Content } = Layout;

const inter = Inter({ subsets: ["latin"] });

// export const metadata: Metadata = {
//     title: "Create Next App",
//     description: "Generated by create next app",
//     icons: [
//         {
//             rel: "icon",
//             url: "/app/favicon.ico",
//         },
//     ],
// };

export default function RootLayout({
    children,
}: {
    children: React.ReactNode;
}) {
    return (
        <html lang="en">
            <body className={inter.className}>
                <div>
                    <Wagmi>
                        <ContextProvider>
                          <StyledComponentsRegistry>
                            <Layout>
                                <Header />
                                <Content style={{ minHeight: "100vh" }}>
                                    {children}
                                </Content>
                                <Footer />
                            </Layout>
                          </StyledComponentsRegistry>
                        </ContextProvider>
                    </Wagmi>
                </div>
            </body>
        </html>
    );
}
