"use client"
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "@/styles/globals.css";
import "@/styles/globals.scss";
import React from "react";
import { Wagmi } from "./wagmi";

const inter = Inter({ subsets: ["latin"] });

// export const metadata: Metadata = {
//     title: "Create Next App",
//     description: "Generated by create next app",
//     icons: [
//         {
//             rel: "icon",
//             url: "/app/favicon.ico",
//         },
//     ],
// };

export default function RootLayout({
    children,
}: {
    children: React.ReactNode;
}) {
    return (
        <html lang="en">
            <body className={inter.className}>
                <div>
                    <Wagmi>
                        {children}
                    </Wagmi>
                </div>
            </body>
        </html>
    );
}
